export const NOTABLE_ALUMNI = [
  {
    name: "Arnav Gupta",
    batch: "2021-2025",
    role: "",
    current: "Google",
    link: "https://www.linkedin.com/in/arnav-gupta-b1715121b",
  },
  {
    name: "Kashvi Garg",
    batch: "2021-2025",
    role: "",
    current: "Google",
    link: "https://www.linkedin.com/in/kashvi-garg-2k3",
  },
  {
    name: "Arham Jain",
    batch: "2021-2025",
    role: "",
    current: "Amazon",
    link: "https://www.linkedin.com/in/arham--jain",
  },
  {
    name: "Ayush Gupta",
    batch: "2020-2024",
    role: "",
    current: "Amazon",
    link: "https://www.linkedin.com/in/ayush-gupta-057368186",
  },
  {
    name: "Sparsh Chadha",
    batch: "2020-2024",
    role: "",
    current: "Zomato",
    link: "https://www.linkedin.com/in/sparsh-chadha-330643204",
  },
  {
    name: "Darpan Chanana",
    batch: "2020-2024",
    role: "",
    current: "Swiggy",
    link: "https://www.linkedin.com/in/darpan-chanana-058914201",
  },
  {
    name: "Sachin Poonia",
    batch: "2020-2024",
    role: "",
    current: "Zeta",
    link: "https://www.linkedin.com/in/sachin-poonia-7482a01bb",
  },
  {
    name: "Aditya Gupta",
    batch: "2021-2025",
    role: "",
    current: "ZS",
    link: "https://www.linkedin.com/in/aditya-guptaa",
  },
  {
    name: "Anjali Gupta",
    batch: "2020-2024",
    role: "",
    current: "ZS",
    link: "https://www.linkedin.com/in/anjali-gupta-254814203",
  },
  {
    name: "Jatin Bhatt",
    batch: "2021-2025",
    role: "",
    current: "Infosys",
    link: "https://www.linkedin.com/in/jatin-bhatt-711aa1194",
  },
  {
    name: "Chaitanya Bisht",
    batch: "2020-2024",
    role: "",
    current: "United Airlines",
    link: "https://www.linkedin.com/in/chaitanyabisht",
  },
  {
    name: "Atharva Rana",
    batch: "2020-2024",
    role: "",
    current: "AngelOne",
    link: "https://www.linkedin.com/in/atharvarana",
  },
  {
    name: "Bhumika Arora",
    batch: "2020-2024",
    role: "",
    current: "Yamaha",
    link: "https://www.linkedin.com/in/bhumika-arora-a0aa92222",
  },
  {
    name: "Jiya Verma",
    batch: "2021-2025",
    role: "",
    current: "ION",
    link: "https://www.linkedin.com/in/jiyaverma",
  },
  {
    name: "Karanjot Singh",
    batch: "2021-2025",
    role: "",
    current: "FNZ",
    link: "https://www.linkedin.com/in/karanjot-s",
  },
  {
    name: "Jai Sukheja",
    batch: "2021-2025",
    role: "",
    current: "Xceedance",
    link: "https://www.linkedin.com/in/jaisukheja02",
  },
  {
    name: "Keshav Chahal",
    batch: "2020-2024",
    role: "",
    current: "Extreme",
    link: "https://www.linkedin.com/in/keshav-chahal-884237125",
  },
  {
    name: "Jivesh Lakhani",
    batch: "2021-2025",
    role: "",
    current: "Candid",
    link: "https://www.linkedin.com/in/jivesh-lakhani",
  },
  {
    name: "Paramhans Singh",
    batch: "2021-2025",
    role: "",
    current: "Optimus",
    link: "https://www.linkedin.com/in/paramhans-singh13",
  },
  {
    name: "Kushagra Jain",
    batch: "2020-2024",
    role: "",
    current: "Stellar",
    link: "https://www.linkedin.com/in/kushagrajain58",
  },
  {
    name: "Ashish Yadav",
    batch: "2021-2025",
    role: "",
    current: "Karya",
    link: "https://www.linkedin.com/in/criticalay",
  },
  {
    name: "Sumit Singh",
    batch: "2020-2024",
    role: "",
    current: "Grayweb",
    link: "https://www.linkedin.com/in/sumit8031",
  },
  {
    name: "Simran Arora",
    batch: "2022-2026",
    role: "",
    current: "hypercode",
    link: "https://www.linkedin.com/in/simran-arora-28125b258",
  },
  {
    name: "Jayant Aggarwal",
    batch: "2022-2026",
    role: "",
    current: "",
    link: "https://www.linkedin.com/in/jayant-aggarwal-418910248",
  },
  {
    name: "Keshav Goyal",
    batch: "2022-2026",
    role: "",
    current: "",
    link: "https://www.linkedin.com/in/keshav-goyal-481004250",
  },
  {
    name: "Pratishtha Gupta",
    batch: "2022-2026",
    role: "",
    current: "",
    link: "https://www.linkedin.com/in/pratishtha-gupta-8a8b29250",
  },
]

export const ALUMNI_IMPACT = [
  { 
    stat: 47,
    suffix: "+",
    label: "Engineers",
    sublabel: "at FAANG & tier-1 companies worldwide"
  },
  { 
    stat: 14,
    suffix: "",
    label: "Founders",
    sublabel: "building startups from zero to scale"
  },
  { 
    stat: 6,
    suffix: "",
    label: "Researchers",
    sublabel: "at top global institutions & labs"
  },
  { 
    stat: 200,
    suffix: "+",
    label: "Alumni",
    sublabel: "contributing to the tech ecosystem"
  },
]
